server:
  port: 8083

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuracion de seguridad y JWT
jwt:
  # Clave secreta codificada en Base64 para firma HMAC-SHA256 (minimo 256 bits)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  # Tiempo de expiracion: 24 horas en milisegundos (86400000 ms)
  expiration: 86400000
